public class DemoController1 {
    
    public string accName;
    public string phoneNum;
    public string email;
    public integer age;
    public integer salary;
    public Date dob;
    public Date joinDate;
    public Boolean isMatch;
    public Boolean isSalProvided;
    
    
    public DemoController1(){
        
    }
    
    /*DemoController1 dc = new DemoController1();
dc.accName='BOA Corporation';
dc.phoneNum='3147573917';
dc.email='mahee@siri.com';
dc.age=34;
dc.salary=10000;
dc.dob=date.valueof('1986-08-18');
dc.joinDate=date.valueof('2020-08-18');
dc.isMatch=false;
dc.isSalProvided=true;
system.debug('ACcount Name'+dc.accName);
system.debug('Phone'+dc.phoneNum);
system.debug('email'+dc.email);
system.debug('Age'+dc.age);
system.debug('salary'+dc.salary);
system.debug('Date Of Borth'+dc.dob);
system.debug('Joined Date'+dc.joinDate);
system.debug('is Matched'+dc.isMatch);
system.debug('is Salary Provided'+dc.isSalProvided);*/
    

}